CREATE TABLE pet_orders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR2(100) NOT NULL,
    quantity NUMBER NOT NULL,
    order_status VARCHAR2(50) NOT NULL
);


CREATE TABLE hotel_reservations (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number NUMBER NOT NULL,
    guest_name VARCHAR2(100) NOT NULL,
    check_in_date DATE NOT NULL,
    check_out_date DATE NOT NULL
);



INSERT INTO hotel_reservations (room_number, guest_name, check_in_date, check_out_date) VALUES
(101, 'Carlos Muñoz', TO_DATE('2024-09-01', 'YYYY-MM-DD'), TO_DATE('2024-09-05', 'YYYY-MM-DD')),
(102, 'Ana Pérez', TO_DATE('2024-09-05', 'YYYY-MM-DD'), TO_DATE('2024-09-10', 'YYYY-MM-DD')),
(103, 'Pedro González', TO_DATE('2024-09-10', 'YYYY-MM-DD'), TO_DATE('2024-09-15', 'YYYY-MM-DD')),
(104, 'Luis Rodríguez', TO_DATE('2024-09-15', 'YYYY-MM-DD'), TO_DATE('2024-09-20', 'YYYY-MM-DD')),
(105, 'Josefa Fernández', TO_DATE('2024-09-20', 'YYYY-MM-DD'), TO_DATE('2024-09-25', 'YYYY-MM-DD')),
(106, 'Matías Rojas', TO_DATE('2024-09-25', 'YYYY-MM-DD'), TO_DATE('2024-09-30', 'YYYY-MM-DD')),
(107, 'Sebastián Díaz', TO_DATE('2024-10-01', 'YYYY-MM-DD'), TO_DATE('2024-10-05', 'YYYY-MM-DD')),
(108, 'Isidora Valdés', TO_DATE('2024-10-05', 'YYYY-MM-DD'), TO_DATE('2024-10-10', 'YYYY-MM-DD'));


INSERT INTO pet_orders (product_name, quantity, order_status) VALUES
('Alimento para Perros', 3, 'Enviado'),
('Juguete para Gatos', 2, 'Entregado'),
('Jaula para Pájaros', 1, 'Procesando'),
('Pecera', 1, 'Enviado'),
('Rascador para Gatos', 2, 'Enviado'),
('Correa para Perros', 1, 'Procesando'),
('Alimento para Gatos', 5, 'Entregado'),
('Collar para Perros', 2, 'Entregado');




CREATE TABLE rooms (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    room_number VARCHAR2(50) UNIQUE NOT NULL,
    room_type VARCHAR2(50) NOT NULL
);



INSERT INTO rooms (room_number, room_type) VALUES ('101', 'Suite');
INSERT INTO rooms (room_number, room_type) VALUES ('102', 'Individual');
INSERT INTO rooms (room_number, room_type) VALUES ('103', 'Doble');
INSERT INTO rooms (room_number, room_type) VALUES ('104', 'Suite');
INSERT INTO rooms (room_number, room_type) VALUES ('105', 'Doble');
INSERT INTO rooms (room_number, room_type) VALUES ('106', 'Individual');
INSERT INTO rooms (room_number, room_type) VALUES ('107', 'Doble');
INSERT INTO rooms (room_number, room_type) VALUES ('108', 'Suite');

